language: go

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.14 lands.
env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - "1.13.x"

# Only clone the most recent commit.
git:
  depth: 1

install: true

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

before_script:
  - go install github.com/gorilla/mux v1.7.3

script:
  - go test -v -race ./...                   # Run all the tests with the race detector enabled