# Add go deb dependencies
# see: https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md


[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

[prune]
  go-tests = true
  unused-packages = true